version: '2'

services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes_from:
            - php
        volumes:
            - ./redis:/data
    db:
        image: mysql
        volumes:
            - ./.data/db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./container-ssh-keys/authorized_keys:/root/.ssh/authorized_keys
        ports:
            - "22:22"
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    elasticsearch:
        image: elasticsearch:2.4.4-alpine
        ports: 
            - 9200:9200
        volumes:
            - ./esdata:/usr/share/elasticsearch/data

    kibana:
        image: kibana:4.6.6
        ports: 
            - 5601:5601
        restart: on-failure
        depends_on: 
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        

